---
title: "HW4"
author: "Louise Lai"
date: "August 13, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
```

```{r}
names <- c("Louise Lai", "Paul Intrevado", "David Uminsky", "Terence Parr", "Jeff Hamrick",
           "paul intrevado", "Intrevado, Paul", "Intrevad0 Paul", "Queen Elizabeth II", 
           "Queen Elizabeth 2nd", "Queen Elizabeth 2", "John Paul Euclid Rumpel", "britishDudeThatSitsInTheBackOfTheClass")

nameChanger <- function(name){
  nameSplit <-  unlist(strsplit("Louise Poopy Lai", "\\s+")) # regex used to handle case where space between name is more than one
  n <- length(nameSplit)
  if(n > 2){
    warning("input non-conforming!\n")
  }
  
  firstName <- tolower(nameSplit[1])
  lastName <- tolower(nameSplit[n])
  
  firstLetter <- str_match(firstName, "[a-z]")
  lastLetter <- str_match(lastName, "[a-z]")
  superlastLetter <- str_match(stringi::stri_reverse(lastName), "[a-z]")
  
  # first chart
  firstChart <- strsplit("Stinky Lumpy Buttercup Gidget Crusty Greasy Fluffy Cheeseball Chim.Chim Poopsie Flunky Booger Pinky Zippy Goober Doofus Slimy Loopy Snotty Falafel Dorky Squeezeit Oprah Skipper Dinky Zsa-Zsa", " ")
  names(firstChart) <- letters[1:26]

  # second chart
  firstChart <- strsplit("Stinky Lumpy Buttercup Gidget Crusty Greasy Fluffy Cheeseball Chim.Chim Poopsie Flunky Booger Pinky Zippy Goober Doofus Slimy Loopy Snotty Falafel Dorky Squeezeit Oprah Skipper Dinky Zsa-Zsa", " ")
  names(firstChart) <- letters[1:26]
  
  # return
  paste(firstDict[firstLetter], thing2)
}

nameChanger("Louise Poopy Lai")
c(letters[1:6])
```

