---
title: "Homework 3"
subtitle: "Question 1"
author: "Louise Lai"
date: "August 2, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
library(ggplot2)
library(dplyr)
library(magrittr)
library(tidyr)
```

## 1.1
# PDFs
```{r, warning=F}
# generate initial dataframe, arranged by smallest xval first
PDFs <- as.data.frame(runif(1000, 0.0, 1.0))
colnames(PDFs) <- "xValue"

PDFs %<>% 
  arrange(xValue)
  
# store given alphas and betas
alphas <- c(0.5, 5, 1, 2, 2)
betas <- c(0.5, 1, 3, 2, 5)

# start filling DF!
generatePDFs <- function(df, alphaArray, betaArray){
  
  # loop through all 5 given alphas/betas
  for(i in 1:5){
    a <- alphaArray[i]
    b <- betaArray[i]
    
    # extract x values
    xVals <- df$xValue
    betaDistribution <- c()
    
    # start filling the distribution vector
    for(k in 1:length(xVals)){
       betaDistribution[k] <- dbeta(xVals[k], a, b)
    }
    
    # convert distribution vector into df column
    df[[i+1]] <- betaDistribution
  }
  names(df) <-  c("xValue", "B1", "B2", "B3", "B4", "B5")
  return(df)
}

PDFs <- generatePDFs(PDFs, alphas, betas)

PDFs %>% 
  ggplot( aes(x=xValue)) +
    geom_line(aes(y=B1, color='1')) + 
    geom_line(aes(y=B2, color='2')) +
    geom_line(aes(y=B3, color='3')) + 
    geom_line(aes(y=B4, color='4'))+ 
    geom_line(aes(y=B5, color='5')) +
    scale_color_discrete(name="", labels=c(bquote(alpha==0.5~","~beta==0.5),
                                           bquote(alpha==5~","~beta==1),
                                           bquote(alpha==1~","~beta==3),
                                           bquote(alpha==2~","~beta==3),
                                           bquote(alpha==2~","~beta==5))) + 
  xlab("x-value") + 
  ylab("Density Function Value") +
  ylim(0, 3.5) +
  labs(caption="Beta Distributions Governed by Alpha and Beta")
```

\newpage
## 1.2
# CDFs
```{r}

generateCDFs <- function(df, alphaArray, betaArray){
  
  # loop through all 5 given alphas/betas
  for(i in 1:5){
    a <- alphaArray[i]
    b <- betaArray[i]
    
    # extract x values
    xVals <- df$xValue
    betaCumulative <- c()
    
    # start filling the cumulative vector
    for(k in 1:length(xVals)){
       betaCumulative[k] <- qbeta(xVals[k], a, b)
    }
    
    # convert distribution vector into df column
    df[[i+5+1]] <- betaCumulative
  }
  
  names(df) <-  c("xValue", "B1", "B2", "B3", "B4", "B5",
                  "BC1", "BC2", "BC3", "BC4", "BC5")
  return(df)
}

PDFCDF <- generateCDFs(PDFs, alphas, betas)

ggplot(data=PDFCDF, aes(x=xValue)) +
  geom_area(aes(y=BC1, color="1", fill="1"), alpha=0.15) +
  geom_area(aes(y=BC2, color="2", fill="2"), alpha=0.15) +
  geom_area(aes(y=BC3, color= "3", fill="3"), alpha=0.15) +
  geom_area(aes(y=BC4, color ="4", fill="4"), alpha=0.15) +
  geom_area(aes(y=BC5, color = "5", fill="5"), alpha=0.15) +
  scale_color_discrete(name="", labels=c(bquote(alpha==0.5~","~beta==0.5),
                                         bquote(alpha==5~","~beta==1),
                                         bquote(alpha==1~","~beta==3),
                                         bquote(alpha==2~","~beta==3),
                                         bquote(alpha==2~","~beta==5))) + 
  scale_fill_discrete(guide=FALSE) +
  xlab("x-value") + 
  ylab("Cumulative Distribution") +
  labs(caption="Cumulative Density of Beta Function Governed by Alpha and Beta") 

```

\newpage
## 1.3
# PDFs & CDFs
```{r}

names(PDFCDF) <-  c("xValue", "PDF 1", "PDF 2", "PDF 3", "PDF 4", "PDF 5",
                  "CDF 1", "CDF 2", "CDF 3", "CDF 4", "CDF 5")

PDFCDF %>% 
  gather(-xValue, key='var', value="value") %>% 
  ggplot(aes(x=xValue, y = value)) +
    geom_line() + 
    scale_color_discrete(name="", labels=c(bquote(alpha==0.5~","~beta==0.5),
                                         bquote(alpha==5~","~beta==1),
                                         bquote(alpha==1~","~beta==3),
                                         bquote(alpha==2~","~beta==3),
                                         bquote(alpha==2~","~beta==5))) + 
  facet_wrap(~ var, scales="free", ncol=5) +
  xlab("x-value") +
  ylab("Density/Cumulative") +
  labs(caption="PDFs and CDFs of Beta Governed by Alpha and Beta") 
  


```
